"""empty message

Revision ID: 0d6a9fe52538
Revises: 5f6282ca952a
Create Date: 2023-05-26 12:35:25.444063

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0d6a9fe52538'
down_revision = '5f6282ca952a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
