"""empty message

Revision ID: 31c7cdf88a7d
Revises: 996261eb2371
Create Date: 2023-05-23 10:54:34.244177

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '31c7cdf88a7d'
down_revision = '996261eb2371'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
