"""empty message

Revision ID: 5f6282ca952a
Revises: a1e3b1477e18
Create Date: 2023-05-26 12:35:13.928179

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '5f6282ca952a'
down_revision = 'a1e3b1477e18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('key_pairs', sa.LargeBinary(), nullable=True))
    op.drop_column('user', 'private_key')
    op.drop_column('user', 'user_type')
    op.drop_column('user', 'pub_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pub_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('user_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('private_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user', 'key_pairs')
    # ### end Alembic commands ###
